name: Test Blog Notebooks
on: [push]
jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Test notebooks
        run: |
          pip install papermill
          papermill adding-a-dimension-to-a-tensor-in-pytorch.ipynb - > /dev/null
